# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
stages:
- stage: Deploy
  pool: 
   name: Default
   demands:
    - Agent.Name -equals JORDAN-PC
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'C:\work\_test\other-test2'
        Contents: '**'
        TargetFolder: '.'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        vstsFeed: 'd30db029-00bc-4631-af4a-cd190b820194/0b5164d2-af62-4e71-9ccb-662cb13af499'
        includeNuGetOrg: false

    - task: CmdLine@2
      inputs:
        script: |
          echo hello
          cd other-test\
          dotnet build
          cd bin\debug
          other-test.exe

    
    

    

